name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
    - name: Build the Docker image
      run: |
        # Strip git ref prefix from version
        IMG_TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && IMG_TAG=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$IMG_TAG" == "master" ] && IMG_TAG=latest

        IMG_NAME="mysql"
        echo IMG_TAG=$IMG_TAG
        echo IMG_NAME=$IMG_NAME
        
        docker build . --file Dockerfile --tag docker.pkg.github.com/mysql-collections/mysql-binlog/$IMG_NAME:$IMG_TAG
        docker push "docker.pkg.github.com/mysql-collections/mysql-binlog/$IMG_NAME:$IMG_TAG"

